name: Build Plugin Pre-Release

on:
  release:
    types: [ prereleased ]

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        uses: php-actions/composer@v2
        with:
          dev: no

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: |
          npm ci
          sudo npm run build
      - name: Generate plugin artifact
        run: |
          mkdir -p release/plausible-analytics
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/plausible-analytics/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/plausible-analytics.zip" .
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/plausible-analytics.zip
          asset_name: plausible-analytics.zip
          asset_content_type: application/zip